/*Each new term an the Fibonabci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55,  89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

(function main() {
  let a = (b = 1);
  let sum = 0;
  const ceil = 4000000;
  while (b <= ceil) {
    const c = a + b;
    if (c % 2 === 0) {
      sum += c;
    }
    a = b;
    b = c;
  }
  console.log(sum);
})();
